/*
Copyright 2011 Robert Marmorstein <robert@narnia.homeunix.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of 
the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

Portions of this code were automatically generated by kapptemplate 
which was written by Kevin Krammer <kevin@akonadi-project.org>
*/

#include <KDockFactoryBase.h>
#include "variable_docker_factory.h"
#include "variable_docker_widget.h"

VariableDockerWidget* VariableDockerFactory::createDockWidget(){
	VariableDockerWidget* myWidget = new VariableDockerWidget();
	myWidget->setObjectName(id());
	return myWidget;
}
